FROM ubuntu:xenial

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
	python3 \
	python3-pip \
	python3-dev \
	libssl-dev \
	libffi-dev

RUN pip3 install kubernetes
RUN pip3 install requests

ADD ./cfg/config /root/.kube/config

ADD ./code /code

WORKDIR /code

ENTRYPOINT ["python3","./main.py"]

