kind: PersistentVolume
apiVersion: v1
metadata:
  name: tetris-volume-v1
  namespace: kube-system
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/tetris/"

