kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tetris-claim-v1
  namespace: kube-system
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

