apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-stressor
  labels:
    app: stressor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stressor
  template:
    metadata:
      labels:
        app: stressor
    spec:
      containers:
      - name: stressor
        image: caffiendd/stressng
        command: ["/bin/bash", "-c"]
        args: ["/usr/bin/mem-run.sh cpu"]
        volumeMounts:
        - mountPath: "/var/log"
          name: tetris-pv-storage
      volumes:
      - name: tetris-pv-storage
        persistentVolumeClaim:
         claimName: tetris-pv-claim