- hosts: K8master
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  tasks:
          - debug: msg="Downloading kubelet.conf"
          - fetch:
                  src: /etc/kubernetes/admin.conf
                  dest: downloads/
                  flat: yes

- name: Setting up Kubsetup 
  hosts: Kubsetup
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Create login user
      user:
        name: "{{ item }}"
        append: yes
        state: present
        shell: /bin/bash       # Defaults to /bin/bash
        system: no             # Defaults to no
        createhome: yes        # Defaults to yes
      with_items: "{{ hostvars[inventory_hostname]['users'] | default([]) }}"

    - name: Creating .kube folder
      command: mkdir "/home/{{item}}/.kube"
      args:
        creates: "/home/{{item}}/.kube"
      with_items: "{{ hostvars[inventory_hostname]['users'] | default([]) }}"

    - name: uploading kubelet
      copy:
              src: downloads/admin.conf
              dest: "/home/{{item}}/.kube/config"
      with_items: "{{ hostvars[inventory_hostname]['users'] | default([]) }}"

    - name: setting kubelet permissions
      command: "chown {{item}}:{{item}} /home/{{item}}/.kube/config"
      with_items: "{{ hostvars[inventory_hostname]['users'] | default([]) }}"

    - name: adding user to docker group
      command: "usermod -a -G docker {{ item }}"
      with_items: "{{ hostvars[inventory_hostname]['users'] | default([]) }}"
